{ "display_name": "Pivotal Cloud Foundry",
  "description": "Monitor Pivotal Cloud Foundry using SignalFx's integration with the Pivotal JMX Bridge.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/cloudfoundry",
  "code": "https://github.com/signalfx/cloudfoundry-integration",
  "featured": true,
  "data_signature": "metric_source:\"cloudfoundry\"",
  "logo_large": "/images/repos/cloudfoundry/img/integrations_cloudfoundry%402x.png",
  "logo_small": "/images/repos/cloudfoundry/img/integrations_cloudfoundry.png",
  "in_app_categories": ["servicesMonitored"]
}
