apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: signalfx-agent
    labels:
        version: v1.0.0-beta-1
        app: signalfx-agent
spec:
    selector:
        matchLabels:
            app: signalfx-agent
    template:
        metadata:
            labels:
                app: signalfx-agent
                version: v1.0.0-beta-1
        spec:
            hostNetwork: true
            containers:
            - name: signalfx-agent
              image: quay.io/signalfx/signalfx-agent:1.0.0-beta-1
              securityContext:
                privileged: true
              volumeMounts:
                - mountPath: /mnt/templates
                  name: templates
                - mountPath: /mnt/services
                  name: services
                - mountPath: /mnt/config
                  name: config
                - mountPath: /hostfs
                  name: hostfs
                  readOnly: true
                - mountPath: /mnt/proc
                  name: proc
                  readOnly: true
                - mountPath: /var/run/docker.sock
                  name: docker
                  readOnly: true
                - mountPath: /mnt/etc
                  name: etc
                  readOnly: true
              env:
              # Please remove this environment variable for Kubernetes versions prior to v1.4
              - name: KUBERNETES_NODE_NAME
                valueFrom:
                    fieldRef:
                        fieldPath: spec.nodeName
              # Please remove this environment variable for Kubernetes versions prior to v1.4
              - name: SFX_PLUGINS_KUBERNETES_HOSTURL
                value: https://$(KUBERNETES_NODE_NAME):10250
              - name: SFX_API_TOKEN
                valueFrom:
                    secretKeyRef:
                        name: signalfx
                        key: api-token
              - name: SFX_MERGE_CONFIG
                value: /etc/signalfx/kubernetes-defaults.yaml:/mnt/config/merge.yml
            volumes:
              - name: templates
                configMap:
                  name: signalfx-templates
              - name: services
                configMap:
                  name: signalfx-services
              - name: config
                configMap:
                  name: signalfx-agent
              - hostPath:
                  path: /
                name: hostfs
              - hostPath:
                  path: /proc
                name: proc
              - hostPath:
                  path: /var/run/docker.sock
                name: docker
              - hostPath:
                  path: /etc
                name: etc
